/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FinishedItem: typeof import('./src/components/finishedItem.vue')['default']
    FinishedSample: typeof import('./src/components/FinishedSample.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IncomeFaq: typeof import('./src/components/IncomeFaq.vue')['default']
    RechargeFaq: typeof import('./src/components/RechargeFaq.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
