export const tabNames = {
   tab1: "成品样片",
   tab2: "窗帘布料",
   tab3: "窗帘杆",
   tab4: "配件",
}


function generateDescImages(fileName: string, count: number) {
   return Array.from({ length: count }, (_, i) => ({
      descImage: new URL(`../assets/finishedSample/${fileName}/desc_image${i + 1}.png`, import.meta.url).href
   }))
}

export const finishSampleData = [
   {
      id: 1,
      title: "阳光灿烂的林间",
      loveValue: 200,
      image: new URL('@/assets/finishedSample/image1.png', import.meta.url).href,
      date: "2025/10/01",
      descriptionData: generateDescImages('description1', 4),
      price: "299¥/米",
      productDescription: "这款窗帘采用高品质面料，具有良好的遮光效果和透气性，适合各种风格的家居环境。其独特的设计和色彩搭配，为您的房间增添一份温馨与舒适。",
      starNumber: 4.8,
      Exposure: 25,
   },
   {
      id: 2,
      title: "北欧极简风",
      loveValue: 185,
      image: new URL('../assets/finishedSample/image2.png', import.meta.url).href,
      date: "2025/10/03",
      descriptionData: generateDescImages('description2', 4),
      price: "259¥/米",
      productDescription: "采用简约素色布料，低饱和度色彩搭配柔和光线，营造干净自然的居家氛围，适合现代极简风格装修。",
      starNumber: 4.7,
      Exposure: 22,
   },
   {
      id: 3,
      title: "法式优雅格调",
      loveValue: 312,
      image: new URL('../assets/finishedSample/image3.png', import.meta.url).href,
      date: "2025/10/05",
      descriptionData: generateDescImages('description3', 4),
      price: "329¥/米",
      productDescription: "采用轻盈蕾丝与精致刺绣，法式优雅尽显。柔和的奶白与金色边饰，为空间增添浪漫气息。",
      starNumber: 4.9,
      Exposure: 31,
   },
   {
      id: 4,
      title: "都市灰调空间",
      loveValue: 278,
      image: new URL('../assets/finishedSample/image4.png', import.meta.url).href,
      date: "2025/10/06",
      descriptionData: generateDescImages('description4', 4),
      price: "289¥/米",
      productDescription: "以高级灰为主调，搭配轻纹理布料，质感细腻，完美融入现代都市风格的居家环境。",
      starNumber: 4.6,
      Exposure: 27,
   },
   {
      id: 5,
      title: "蓝色海岸之梦",
      loveValue: 340,
      image: new URL('../assets/finishedSample/image5.png', import.meta.url).href,
      date: "2025/10/08",
      descriptionData: generateDescImages('description5', 4),
      price: "319¥/米",
      productDescription: "灵感源自地中海海岸，以清新蓝白色为主，透气面料带来舒适通风体验，让房间如同海风拂面。",
      starNumber: 4.9,
      Exposure: 33,
   },
   {
      id: 6,
      title: "田园小花时光",
      loveValue: 198,
      image: new URL('../assets/finishedSample/image6.png', import.meta.url).href,
      date: "2025/10/10",
      descriptionData: generateDescImages('description6', 4),
      price: "269¥/米",
      productDescription: "印花面料搭配浅米底色，营造自然清新感，让阳光洒入房间的每一角，充满温馨生活气息。",
      starNumber: 4.5,
      Exposure: 20,
   },
   {
      id: 7,
      title: "摩登轻奢系列",
      loveValue: 410,
      image: new URL('../assets/finishedSample/image7.png', import.meta.url).href,
      date: "2025/10/11",
      descriptionData: generateDescImages('description7', 4),
      price: "359¥/米",
      productDescription: "采用金丝提花布料，配合丝滑质地，展现现代轻奢气质，适合高端客厅与卧室空间。",
      starNumber: 5.0,
      Exposure: 40,
   },
   {
      id: 8,
      title: "日式禅意之境",
      loveValue: 233,
      image: new URL('../assets/finishedSample/image8.png', import.meta.url).href,
      date: "2025/10/12",
      descriptionData: generateDescImages('description8', 4),
      price: "279¥/米",
      productDescription: "以棉麻材质为主，搭配自然原木色调，柔和光线中透露宁静与平衡之美，适合追求极简生活的你。",
      starNumber: 4.6,
      Exposure: 24,
   },
   {
      id: 9,
      title: "梦幻星空系列",
      loveValue: 365,
      image: new URL('../assets/finishedSample/image9.png', import.meta.url).href,
      date: "2025/10/13",
      descriptionData: generateDescImages('description9', 4),
      price: "309¥/米",
      productDescription: "灵感源自星空夜色，微光点缀的质感布面营造浪漫梦幻的氛围，让夜晚更显温柔与宁静。",
      starNumber: 4.8,
      Exposure: 35,
   },
   {
      id: 10,
      title: "自然原野系列",
      loveValue: 280,
      image: new URL('../assets/finishedSample/image10.png', import.meta.url).href,
      date: "2025/10/15",
      descriptionData: generateDescImages('description10', 4),
      price: "299¥/米",
      productDescription: "灵感源于大自然原野色彩，以米黄与浅绿为主色调，质朴自然，带来舒适悠然的生活体验。",
      starNumber: 4.7,
      Exposure: 28,
   },
];